### ISSUE TITLE
closeAllContextMenus not possible with ngx-contextmenu without ContextMenuDirective

### ISSUE THREAD

**Issue by timonkrebs** [PerfectMemory/ngx-contextmenu#18] opened 2023-01-03 21:07 UTC
If you have to open the contextmenu with ContextMenuService.show() 
```  onContextMenu($event: MouseEvent, value) {
    this.contextMenuService.show(
    this.contextMenuTemplate, 
    {
      x: $event.clientX,
      y: $event.clientY,
      value: value
    })
    $event.preventDefault();
    $event.stopPropagation();
  }
```

The Problem with #9 is still not resolved.  

In my real app it is much more complicated. There it is not possible to work with the [contextMenu] directive. Therefore it is not possible to use the close method. It is important to close all contextmenus if some action is triggered. It can not only close the contextmenus opened by the directive. If the [context-menu-stack.service](https://github.com/PerfectMemory/ngx-contextmenu/blob/master/projects/ngx-contextmenu/src/lib/services/context-menu-stack/context-menu-stack.service.ts) would be exposed this could be done very easily.

**Expected behavior**
It would be nice to have a closeAll() method on the contextMenuService.
```
 this.contextMenuService.closeAll()
```
Or even better:
The [context-menu-stack.service](https://github.com/PerfectMemory/ngx-contextmenu/blob/master/projects/ngx-contextmenu/src/lib/services/context-menu-stack/context-menu-stack.service.ts) would be exposed.

**Stackblitz Example**
https://stackblitz.com/edit/node-mr7qba?file=src%2Fapp%2Fapp.component.html

**To Reproduce**
1. Wait until running
2. Click on any node
3. Its not possible to close it with the directive because it is opened by the contextMenuService
4. Context Menu does not close when tree is expanded

**Comment by timonkrebs** [comment] 2023-01-03 21:32
#19 would solve all my problems. We also have checks if ContextMenus exist and this would also be solved by [context-menu-stack.service isEmpty()](https://github.com/PerfectMemory/ngx-contextmenu/blob/master/projects/ngx-contextmenu/src/lib/services/context-menu-stack/context-menu-stack.service.ts#:~:text=public%20isEmpty()%3A%20boolean%20%7B) 

At the moment we still have to use [v/7.0.1](https://www.npmjs.com/package/@perfectmemory/ngx-contextmenu/v/7.0.1) because it does not work with newer versions.

**Comment by sroucheray** [comment] 2023-01-06 08:48
Hi @timonkrebs,

Thanks for challenging the API !

I am always reluctant to add new public APIs (it involves a new minor version, then people ask for it to be backported to older versions, it is more work as maintenance in the future). I won't make the stack service a public API because it was designed to be private and would open to much of internal implementation.

That said I am **not** totally against adding new public API if it addresses a unsupported use case. Why not adding a `closeAll` method on the context menu service that would call the stack menu service. I would like to know a bit more about your usage of isEmpty ? Can you elaborate on this use case ?

**Comment by Brampage** [comment] 2023-01-06 10:33
@timonkrebs you state: 

> In my real app it is much more complicated. There it is not possible to work with the [contextMenu] directive. Therefore it is not possible to use the close method.

Couldn't you just do a `ViewChildren` on `ContextMenuDirective`? Then loop over all the contextMenus and call `close`?

Something like this (don't know if this code works, but you get the idea):
  
```
@ViewChildren(ContextMenuDirective)
 contextMenus: ContextMenuDirective<any>[];

someAction(): void {
    contextMenus.forEach((c) => c.close());
}
```

**Comment by timonkrebs** [comment] 2023-01-09 09:52
@Brampage We use a library that only exposes an event that can be used to show the contextmenu. Therefore we do not have a ContextMenuDirective since i have to show the context menu via the contextMenuService and not the ContextMenuDirective. 

@sroucheray The UseCase for the is  isEmpty is that we would like to prevent some shortcuts if a contextmenu is open. For example we do not want to let the user change the edit mode of the app if a contextmenu is open. With isEmpty we could prevent Ctrl + Y to trigger editmode change if a contextmenu is present.

It probably is even better if the closeAll method would be on the context menu service. Then the isEmpty method could also be on the context menu service.

**Comment by sroucheray** [comment] 2023-01-09 10:10
@timonkrebs ok, it seems a legitimate use case.

I would say we need two new methods on the context menu service
- `closeAll(): void` which would use the closeAll method of the stack service
- `hasOpenMenu(): boolean` which would use the isEmpty method of the stack service. 

If you will you can provide a PR for that, it should include implementation with proper comments and unit tests. We should also update the documentation but it can be done later.

**Comment by timonkrebs** [comment] 2023-01-09 10:30
perfect thanks! Where can the documentation be updated?

**Comment by sroucheray** [comment] 2023-01-09 10:38
The project use storybook for the documentation. If you know it you can add a story and a new entry in the documentation menu for the service API. Otherwise I'll do it myself. 
https://github.com/PerfectMemory/ngx-contextmenu/tree/master/src/stories

**Comment by timonkrebs** [comment] 2023-01-12 16:57
I did update the PR #19

**Comment by sroucheray** [comment] 2023-01-16 08:30
Merged ! Thanks @timonkrebs

**Closed as completed by sroucheray** 2023-01-16 08:30 UTC

**Comment by mhfahmy** [comment] 2023-02-09 17:11
Hi guys, thanks for the work being done so far.
question: is it possible to get the closeAll() functionality on version 14?

**Comment by sroucheray** [comment] 2023-02-10 10:28
Hi @MoeFahmy,

Sure we can backport the feature to version 14, it's a rather small feature. Would you like to make a PR for that ? I won't have time to do it soon.
